### ISSUE TITLE
Emit more helpful error message?

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc-tex2svg#2]
I tried running it on a large file (book-size), and there's a lot of error message, a sample is like this:

```bash
Error: TypeError: math.replace is not a function
    at StartQueue (/usr/local/lib/node_modules/mathjax-node/lib/mj-single.js:668:17)
    at Function.execute (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
```

Probably it is some syntax it is complaining about (I also configure the MathJax manually), but unlike MathJax that will show the wrong syntax in red, MathJax-node will just choke and complain. So it would be helpful by showing some error message. Perhaps if there's an error, print the Math sent into MathJax-node?

**Comment by jgm** [comment]
Closed by efe1390cd3d30659268455ea1549fdb5877f9f6d
